services:

  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.development.local
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: cedroadv_ad
      POSTGRES_PASSWORD: cedropass123
      POSTGRES_DB: cedroadv_db
    volumes:
      - postgres_data:/var/lib/postgresql
  
volumes:
  postgres_data: