export default () => ({
    DATABASE_URL: process.env.DATABASE_URL!,
    JWT_SECRET: process.env.JWT_SECRET!,
    R2_ACCOUNT_ID: process.env.R2_ACCOUNT_ID!,
    R2_ACCESS_KEY_ID: process.env.R2_ACCESS_KEY_ID!,
    R2_SECRET_ACCESS_KEY: process.env.R2_SECRET_ACCESS_KEY!,
    R2_BUCKET_NAME: process.env.R2_BUCKET_NAME!,
    R2_PUBLIC_URL: process.env.R2_PUBLIC_URL!,
    R2_S3_API: process.env.R2_S3_API!,
    NODE_ENV: process.env.NODE_ENV!,
    SMTP_HOST: process.env.SMTP_HOST!,
    SMPT_PORT: process.env.SMPT_PORT!,
    SMTP_USER: process.env.SMTP_USER!,
    SMTP_PASS: process.env.SMTP_PASS!,
    BOOKINGS_EMAIL: process.env.BOOKINGS_EMAIL!,
});